from flask import Blueprint, jsonify, render_template_string
from bson import ObjectId
from db import agents_col

openapi_bp = Blueprint('openapi', __name__)

AGENT_NOT_FOUND = 'Agent not found'
INVALID_ID = 'Invalid ID agent'


@openapi_bp.route('/api/agents/<agent_id>/openapi.json', methods=['GET'])
def agent_openapi_spec(agent_id):
    try:
        agent = agents_col.find_one({'_id': ObjectId(agent_id)})
    except Exception:
        return jsonify({'error': INVALID_ID}), 400

    if not agent:
        return jsonify({'error': AGENT_NOT_FOUND}), 404

    path = f'/api/public/agents/{agent_id}/chat'
    operation = {
        'summary': f'Ask "{agent.get("name", "this agent")}" a question',
        'requestBody': {
            'required': True,
            'content': {
                'application/json': {
                    'schema': {
                        'type': 'object',
                        'required': ['question'],
                        'properties': {
                            'question': {'type': 'string', 'example': 'What is this document about?'}
                        }
                    }
                }
            }
        },
        'responses': {
            '200': {
                'description': 'Answer generated by the agent',
                'content': {
                    'application/json': {
                        'schema': {
                            'type': 'object',
                            'properties': {'answer': {'type': 'string'}}
                        }
                    }
                }
            },
            '400': {'description': 'Invalid request body'},
            '401': {'description': 'Missing or invalid API key'}
        }
    }

    spec = {
        'openapi': '3.0.0',
        'info': {
            'title': f'{agent.get("name", "Agent")} API',
            'version': '1.0.0'
        },
        'paths': {path: {'post': operation}}
    }

    if agent.get('api_key_required', False):
        operation['security'] = [{'ApiKeyAuth': []}]
        spec['components'] = {
            'securitySchemes': {
                'ApiKeyAuth': {'type': 'apiKey', 'in': 'header', 'name': 'X-API-Key'}
            }
        }

    return jsonify(spec), 200


SWAGGER_HTML = """<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Agent API docs</title>
  <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5/swagger-ui.css" />
</head>
<body>
  <div id="swagger-ui"></div>
  <script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js"></script>
  <script>
    window.onload = () => {
      window.ui = SwaggerUIBundle({
        url: '/api/agents/{{ agent_id }}/openapi.json',
        dom_id: '#swagger-ui',
      })
    }
  </script>
</body>
</html>"""


@openapi_bp.route('/docs/<agent_id>', methods=['GET'])
def agent_docs(agent_id):
    return render_template_string(SWAGGER_HTML, agent_id=agent_id)